[package]
name = "rusty-art"
version = "0.1.0"
edition = "2021"
authors = ["Etienne Collin <contact@etiennecollin.com>"]

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"

[[bin]]
name = "birds"
path = "src/birds.rs"

